version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=appointments
      - PORT=3000
      - NODE_ENV=production
      - HONEYCOMB_API_KEY=FWqTs3rQTmE1er45EdCRrD
    networks:
      - nest_network  
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appointments
    networks:
      - nest_network
networks:
  nest_network: